{% set name = "SLiM" %}
{% set version = "4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MesserLab/SLiM/archive/v{{ version }}.tar.gz
  sha256: 52aaa0296221af706eacf648cbd8fe0ef7ffb9a7462e84605845e287f5bc332b

build:
  number: 0

requirements:
  build:
    - make  # [not win]
    - m2-make  # [win]
    - cmake
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    # Full posix environment.
    - m2-base  # [win]

test:
  commands:
    - slim -testSLiM
    - slim -testEidos
    - eidos -testEidos

about:
  home: http://messerlab.org/slim/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Forward-time population genetics simulator

  description: |
    SLiM is an evolutionary simulation framework that combines a powerful engine
    for population genetic simulations with the capability of modeling
    arbitrarily complex evolutionary scenarios.
  doc_url: https://messerlab.org/slim/
  dev_url: https://github.com/MesserLab/SLiM

extra:
  recipe-maintainers:
    - jeromekelleher
    - bhaller
    - petrelharp
