{% set name = "SLiM" %}
{% set version = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MesserLab/SLiM/archive/v{{ version }}.tar.gz
  sha256: 763594281f8d5b66bfea868031c1f4525fd1fd73c7bc60dbc257de16691b30e6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - slim -v
    - eidos -v

about:
  home: http://messerlab.org/slim/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forward-time population genetics simulator

  description: |
    SLiM is an evolutionary simulation framework that combines a powerful engine
    for population genetic simulations with the capability of modeling
    arbitrarily complex evolutionary scenarios.
  doc_url: https://messerlab.org/slim/
  dev_url: https://github.com/MesserLab/SLiM

extra:
  recipe-maintainers:
    - jeromekelleher
    - bhaller
    - petrelharp
