{% set name = "SLiM" %}
{% set version = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MesserLab/SLiM/archive/v{{ version }}.tar.gz
  sha256: 2fae88f22a467e1fd3b7bc1d7965e844ed7ad9fea9b677e12148a99be8f63268

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - slim -v
    - eidos -v

about:
  home: http://messerlab.org/slim/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forward-time population genetics simulator

  description: |
    SLiM is an evolutionary simulation framework that combines a powerful engine
    for population genetic simulations with the capability of modeling
    arbitrarily complex evolutionary scenarios.
  doc_url: https://messerlab.org/slim/
  dev_url: https://github.com/MesserLab/SLiM

extra:
  recipe-maintainers:
    - jeromekelleher
    - bhaller
    - petrelharp
